@startuml
[*] -> LISTEN : makeListener()
LISTEN : Waiting for a request to arrive
LISTEN --> PROCESS : Proceed() (calls process())
PROCESS : Processing a request
PROCESS --> FINISH : Proceed() (calls finish())
FINISH : Response has been sent successfully, object destroyed
FINISH --> [*]
@enduml
